chinook_data_platform:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: chinook_db_dev
      keyfile: "{{ env_var('DBT_BQ_KEYFILE') }}"
      location: US
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: chinook_db
      keyfile: "{{ env_var('DBT_BQ_KEYFILE') }}"
      location: US
      threads: 8
      job_execution_timeout_seconds: 600
      job_retries: 3
      priority: batch

  target: dev
