chinook_data_platform:
  outputs:
    dev:
      dataset: chinook_db
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: D:\Workspace\chinook-data-platform\keys\chinook-data-platform.json
      location: US
      method: service-account
      priority: interactive
      project: cs-host-8de95983f3a147dc969af4
      threads: 1
      type: bigquery
  target: dev